### ISSUE TITLE
Change "Title" to include description for better bookmarks and search engine results

### ISSUE THREAD

**Issue by gene1wood** [gogits/gogsweb.peach#4]
Currently the [title](https://github.com/gogs/gogsweb.peach/blob/835a0f9eabb40ca4a20b7c67fe38a15ce2973ca0/templates/base.html#L32) tag on https://gogs.io/ is
```
Gogs
```

Would you be open to changing it to something like

```
Gogs - A painless self-hosted Git service
``` 

So that the terms "git" and "self-hosted" show up in bookmark searches in browsers (e.g. the Firefox awesome bar) and in search results on search engines?

**Comment by unknwon** [comment]
Yes, sure, I'll do it.

**Comment by unknwon** [comment]
Done: https://gogs.io/
